In [12]:
import numpy as np

In [16]:
def lambda_2(N):
    lam = np.zeros(((N - 1), (N - 1)))
    for i in range(N - 1):
        for j in range(N - 1):
            if i == j:
                lam[i, j] = -2
            elif i == j + 1:
                lam[i, j] = 1
            elif i == j - 1:
                lam[i, j] = 1
                
    return lam

In [76]:
def lambda_4(N):
    return np.dot(lambda_2(N), lambda_2(N))

In [102]:
def A(Nx, Ny):
    return np.kron(np.eye(Nx - 1), lambda_4(Ny)) + np.kron(lambda_4(Nx), np.eye(Ny - 1)) + 2*np.kron(lambda_2(Nx), lambda_2(Ny))

In [43]:
def v(N):
    M = np.zeros(((N - 1), 2), dtype=np.double)
    M[0, 0] = 1
    M[-1, -1] = 1
    return M

In [63]:
def V1(Nx, Ny):
    return np.kron(v(Nx), np.eye(Ny - 1))

In [68]:
def V2(Nx, Ny):
    return np.kron(np.eye(Nx - 1), v(Ny))

In [69]:
def V(Nx, Ny):
    return np.hstack((V1(Nx, Ny), V2(Nx, Ny)))

In [90]:
def F(N):
    M = np.zeros((N - 1, N - 1))
    for i in range(N - 1):
        for j in range(N - 1):
            M[i, j] = np.sqrt(2/N)*np.sin(np.pi*(i + 1)*(j + 1)/N)
            
    return M

In [24]:
l2 = lambda_2(6)
l2

array([[-2.,  1.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  1., -2.]])

In [77]:
lambda_4(6)

array([[ 5., -4.,  1.,  0.,  0.],
       [-4.,  6., -4.,  1.,  0.],
       [ 1., -4.,  6., -4.,  1.],
       [ 0.,  1., -4.,  6., -4.],
       [ 0.,  0.,  1., -4.,  5.]])

In [26]:
v(5)

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [84]:
M1 = V1(4, 7)
M1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.,

In [85]:
M2 = V2(3, 7)
M2

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [73]:
V(5, 3)

array([[1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
A(4, 5)

array([[14., -6.,  1.,  0., -6.,  1.,  0.,  0.,  1.,  0.,  0.,  0.],
       [-6., 15., -6.,  1.,  1., -6.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 1., -6., 15., -6.,  0.,  1., -6.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  1., -6., 14.,  0.,  0.,  1., -6.,  0.,  0.,  0.,  1.],
       [-6.,  1.,  0.,  0., 15., -6.,  1.,  0., -6.,  1.,  0.,  0.],
       [ 1., -6.,  1.,  0., -6., 16., -6.,  1.,  1., -6.,  1.,  0.],
       [ 0.,  1., -6.,  1.,  1., -6., 16., -6.,  0.,  1., -6.,  1.],
       [ 0.,  0.,  1., -6.,  0.,  1., -6., 15.,  0.,  0.,  1., -6.],
       [ 1.,  0.,  0.,  0., -6.,  1.,  0.,  0., 14., -6.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1., -6.,  1.,  0., -6., 15., -6.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  1., -6.,  1.,  1., -6., 15., -6.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  1., -6.,  0.,  1., -6., 14.]])

In [87]:
Nx = 3
Ny = 4

np.dot(np.dot(V1(Nx, Ny).transpose(), np.linalg.inv(A(Nx, Ny))), V1(Nx, Ny))

array([[0.13675895, 0.09084924, 0.03901459, 0.07983091, 0.07044108,
        0.03471813],
       [0.09084924, 0.17577354, 0.09084924, 0.07044108, 0.11454905,
        0.07044108],
       [0.03901459, 0.09084924, 0.13675895, 0.03471813, 0.07044108,
        0.07983091],
       [0.07983091, 0.07044108, 0.03471813, 0.13675895, 0.09084924,
        0.03901459],
       [0.07044108, 0.11454905, 0.07044108, 0.09084924, 0.17577354,
        0.09084924],
       [0.03471813, 0.07044108, 0.07983091, 0.03901459, 0.09084924,
        0.13675895]])

In [93]:
np.dot(np.dot(np.kron(F(Nx), F(Ny)), A(Nx, Ny)), np.kron(F(Nx), F(Ny))).round(3)

array([[ 1.929, -0.   , -0.   , -0.   , -0.   ,  0.   ],
       [-0.   ,  7.   , -0.   , -0.   , -0.   ,  0.   ],
       [ 0.   ,  0.   , 16.071,  0.   ,  0.   , -0.   ],
       [-0.   , -0.   ,  0.   , 11.101,  0.   ,  0.   ],
       [-0.   , -0.   , -0.   ,  0.   , 19.   , -0.   ],
       [ 0.   , -0.   ,  0.   ,  0.   ,  0.   , 30.899]])

In [103]:
np.dot(np.dot(V(Nx, Ny).transpose(), np.linalg.inv(A(Nx, Ny))), V(Nx, Ny))

array([[0.11919756, 0.08697858, 0.04186416, 0.02329516, 0.0284747 ,
        0.01798393, 0.11919756, 0.04186416, 0.0898552 , 0.04846421,
        0.05224241, 0.03578216, 0.02329516, 0.01798393],
       [0.08697858, 0.16106172, 0.08697858, 0.0284747 , 0.04127909,
        0.0284747 , 0.08697858, 0.08697858, 0.08750381, 0.08750381,
        0.05929246, 0.05929246, 0.0284747 , 0.0284747 ],
       [0.04186416, 0.08697858, 0.11919756, 0.01798393, 0.0284747 ,
        0.02329516, 0.04186416, 0.11919756, 0.04846421, 0.0898552 ,
        0.03578216, 0.05224241, 0.01798393, 0.02329516],
       [0.02329516, 0.0284747 , 0.01798393, 0.11919756, 0.08697858,
        0.04186416, 0.02329516, 0.01798393, 0.05224241, 0.03578216,
        0.0898552 , 0.04846421, 0.11919756, 0.04186416],
       [0.0284747 , 0.04127909, 0.0284747 , 0.08697858, 0.16106172,
        0.08697858, 0.0284747 , 0.0284747 , 0.05929246, 0.05929246,
        0.08750381, 0.08750381, 0.08697858, 0.08697858],
       [0.01798393, 0.0284747 , 0.0

In [98]:
Nx = 5

In [99]:
P = np.zeros((Nx - 1, Nx - 1))
for i in range(Nx - 1):
    for j in range(Nx - 1):
        if i == j:
            P[i, j] = 4
        elif i == j + 1:
            P[i, j] = 1
        elif i == j - 1:
            P[i, j] = 1